# Generated by Django 3.1.5 on 2022-06-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_show_on_front_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_amount',
            field=models.FloatField(default=1000),
        ),
    ]
